### ISSUE TITLE
Consider publishing to Open VSX

### ISSUE THREAD

**Issue by thebearingedge** [AdamCaviness/vs-code-theme-monokai-dark-soda#14]
Hi @AdamCaviness, thanks for the great theme. This one is my ride-or-die for years now.

Would you be open to publishing the extension to [the Open VSX Registry](https://open-vsx.org/) so that it is available to things like GitPod and VS Codium? A while ago I was asked to publish an extension there by a community member and when I finally got around to it 😅, it was very quick and easy.

You [claim a namespace](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace), which is your publisher name via a PR. Then click a couple times in your user account to create a publisher token. Lastly, use their CLI to [publish your extension](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension). 

Anyway, thanks again for the theme. Peace! ✌️

**Comment by AdamCaviness** [comment]
@thebearingedge Hi Tim, happy to do this. I created a namespace claim PR [here](https://github.com/EclipseFdn/open-vsx.org/issues/1738). I also performed the necessary user-related actions on open-vsx.org. I'll revisit and publish ASAP.

**Comment by thebearingedge** [comment]
Sweeeet ty ty

**Comment by AdamCaviness** [comment]
@thebearingedge it's published on [Open VSX Registry now](https://open-vsx.org/extension/AdamCaviness/theme-monokai-dark-soda). 🙌🏼
