### ISSUE TITLE
Unintentional base theme change?

### ISSUE THREAD

**Issue by JakeIsMeh** [AdamCaviness/vs-code-theme-monokai-dark-soda#15]
Hi there! Big fan of the theme.

With 1.1.0, it seems that the base theme is now Atom One Dark.

To my understanding, you've used Atom One Dark as a reference to add support for more tokens/scopes.
In the process, it seems that Atom One Dark colors are also now used for the rest of the interface.
I saw that you replied to a comment on https://github.com/AdamCaviness/vs-code-theme-monokai-dark-soda/commit/39bd882dc6885a51d4f8469e68b3d5a87afb2b2b, however I'm not sure if this means that Atom One Dark will be the base theme going forward.

**Comment by CryZe** [comment]
I was very suprised to see that my VS Code suddenly looked like Atom, glad to hear that it likely was unintentional.

**Comment by AdamCaviness** [comment]
@JakeIsMeh @CryZe I have reverted the colors back to **_exactly_** as they were before. I apologize for the frustration!
