### ISSUE TITLE
Theme Contrast Regressions in New Update

### ISSUE THREAD

**Issue by Brikwerk** [AdamCaviness/vs-code-theme-monokai-dark-soda#16]
Hi there and first off, thanks for supporting this theme over the years!

I'm sorry if this comes off as a bit of a nitpick, however, with the recent update, I've noticed some interface and theme colour changes that seem like a significant departure from the previous overall theme. I think the main interface changes are already mentioned in #15, however, I also wanted to surface contrast changes specifically.

To be clear, I am observing that the IDE background has changed from #242424 to #26282c, the IDE text has changed from #e3e3df to #d3d5d8, and the Python Jupyter Notebook background has changed from #242424 to #2c313a (this list is non-exhaustive, other changes were observed). Overall, these changes have resulted in worse contrast across the board. Using the contrast checker on coolors.co, I am observing a 2-6 point regression for these new foreground/background pairings.

I would like to ask if this is a new direction for this theme or potentially something unintentional? Would it be possible to realign some of the main pairings with the stated colour scheme in the README?

FYI, I am using the latest editions of VSCode (1.77.1) on macOS 13 (MacBook Pro 16, M1).

**Comment by black-eye** [comment]
Same issues here. Are the color changes intentional?

**Comment by AdamCaviness** [comment]
@Brikwerk @black-eye Yes, they were intentional and based on my _subjective_ tastes. There is consensus this is undesired so I have reverted the colors back to **_exactly_** as they were before. I apologize for the frustration!
