### ISSUE TITLE
Syntax Checking is not working anymore?

### ISSUE THREAD

**Issue by lexman1958** [AdamCaviness/vs-code-theme-monokai-dark-soda#17]
Hi,

We are very disappointed that the theme was changed! It has upset all the color and highlights we are so used to. The changes could have been created under a new extension and not altered the existing. This has upset many of us. In fact many of us started to suspect virus infection and started to clean the workstations and reinstall the all the extensions.

Fortunately, one of them did the whole thing and found the problems still persisted. Only then we realized the existing themes have been updated. Sad to say, our feedback is that we do not like the newer version. Is there any way of reverting to the older version? 

The bade party is that we found that the syntax checking has also gone. For example in php, when i type in a variable that does exist, i get a sqiggly underline to show that the variable does not exist. Now it does not work??? This has happen after vs code loaded the latest version of this theme.

**Comment by lexman1958** [comment]
Now we found that the syntax checking has also gone. For eaxmple in php, when i type in a variable that does exist, i get a sqiggly underline to show that the variable does not exist. Now it does not work???

**Comment by Akagire** [comment]
You can install older version. See there
https://code.visualstudio.com/docs/editor/extension-marketplace

<img width="739" alt="スクリーンショット 2023-04-10 12 05 47" src="https://user-images.githubusercontent.com/9305065/230817361-103051a2-8ce3-446f-8bf9-19d1bc1c0185.png">

I'm still using `v1.0.0` by this workaround.

**Comment by AdamCaviness** [comment]
@lexman1958 @Akag I have reverted the colors back to **_exactly_** as they were before. I apologize for the frustration!

**Comment by lexman1958** [comment]
@AdamCaviness 

Thank you for reverting back. It works well and we are back to our old happiness.
